package ru.smith.entity;
// Generated Jun 28, 2017 2:49:16 PM by Hibernate Tools 4.3.1


import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name="author"
    ,catalog="firstproject"
)
@XmlRootElement
public class Author  implements java.io.Serializable {


     private Long id;
     private String fio;
     private List<Book> books;

    public Author() {
    }

	
    public Author(String fio) {
        this.fio = fio;
    }
    public Author(String fio, List<Book> books) {
       this.fio = fio;
       this.books = books;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="fio", nullable=false, length=300)
    public String getFio() {
        return this.fio;
    }
    
    public void setFio(String fio) {
        this.fio = fio;
    }

@OneToMany(fetch = FetchType.LAZY, mappedBy="author")
    public List<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(List<Book> books) {
        this.books = books;
    }
}


