package ru.smith.entity;
// Generated Jul 7, 2017 11:30:21 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Sessions generated by hbm2java
 */
@Entity
@Table(name="sessions"
    ,catalog="firstproject"
)
@XmlRootElement
public class Sessions  implements java.io.Serializable {


     private String sesId;
     private Users users;

    public Sessions() {
    }

    public Sessions(String sesId, Users users) {
       this.sesId = sesId;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="ses_id", unique=true, nullable=false, length=32)
    public String getSesId() {
        return this.sesId;
    }
    
    public void setSesId(String sesId) {
        this.sesId = sesId;
    }

@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name="user_id", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


