package ru.smith.entity;
// Generated Jun 28, 2017 2:49:16 PM by Hibernate Tools 4.3.1



import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="firstproject"
)
@XmlRootElement
public class Users  implements java.io.Serializable {


     private String userName;
     private String userPass;
     private List<Book> books;
     private List<Sessions> sessionses;

    public Users() {
    }

	
    public Users(String userName, String userPass) {
        this.userName = userName;
        this.userPass = userPass;
    }
    public Users(String userName, String userPass, List<Book> books, List<Sessions> sessionses) {
       this.userName = userName;
       this.userPass = userPass;
       this.books = books;
       this.sessionses = sessionses;
    }
   
     @Id 

    
    @Column(name="user_name", unique=true, nullable=false, length=15)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_pass", nullable=false, length=15)
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

@OneToMany(fetch = FetchType.LAZY, mappedBy="users")
    public List<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(List<Book> books) {
        this.books = books;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy="users")
    public List<Sessions> getSessionses() {
        return this.sessionses;
    }
    
    public void setSessionses(List<Sessions> sessionses) {
        this.sessionses = sessionses;
    }


}


